### PR TITLE
New name new pages

### PR DESCRIPTION
**Pull request by thierryk**
Added FAQ + RWD pages (WIP)

### CODE REVIEW

**Comment by src-code** [comment]
I don't think we should use ACSS.io in the header - it's short and convenient to type, but it doesn't really convey any meaning.  I think we should have it be descriptive to what the site is about, which is Atomic CSS.

**Comment by thierryk** [comment]
Not sure about that. I'd think it's important to help people remember the domain name as it won't be "atomiccss"
We have Atomic CSS on the slash box and that could lead people to remember this as the domain name.
No?
 Thierry Koblentz
yo/thierryyo/stencilyo/stencilbugyo/cssworkshop

 

 

     On Thursday, February 26, 2015 11:43 AM, Steve Carlson <notifications@github.com> wrote:
   

 I don't think we should use ACSS.io in the header - it's short and convenient to type, but it doesn't really convey any meaning. I think we should have it be descriptive to what the site is about, which is Atomic CSS.—

**Comment by redonkulus** [comment]
+1 for Atomic CSS ... its the name of the site.

**Comment by thierryk** [comment]
> +1 for Atomic CSS ... its the name of the site.

@redonkulus Whaaaaat? We had Atomic.css in there and if I recall someone said to go with ACSS.io isn't? I didn't change this on my own, I was told that ACSS was better in the header and I said I'll change it because I agreed with the idea. Because - *unlike what you say* - Atomic CSS is **not** the name of the web site. And this is why I mentioned it could be confusing to have that in there. Because as you suggest yourself, people could think it is the name of the web site and could go to atomiccss.io instead of acss.io OR are we saying we should drop acss.io in favor of atomiccss.io? I'm confused now...

**Comment by src-code** [comment]
We will have multiple domains set up to redirect to acss.io, so even if they get the domain wrong, it'll be ok.The more important thing is to have the name of the philosophy be clear, I believe.  We actually had ACSS.io in the header before, but we changed it for the same reasons we're discussing now. :-/ --  
Steve Carlson 
Sr. Frontend Engineer – Homepages & Verticals
@StevenRCarlson 

     On Thursday, February 26, 2015 12:21 PM, Thierry Koblentz <notifications@github.com> wrote:
   

 
+1 for Atomic CSS ... its the name of the site.
@redonkulus Whaaaaat? We had Atomic.css in there and if I recall someone said to go with ACSS.io isn't? I didn't change this on my own, I was told that ACSS was better in the header and I said I'll change it because I agreed with the idea. Because - unlike what you say - Atomic CSS is not the name of the web site. And this is why I mentioned it could be confusing to have that in there. Because as you suggest yourself, people could think it is the name of the web site and could go to atomiccss.io instead of acss.io OR are we saying we should drop acss.io in favor of atomiccss.io? I'm confused now...—

**Comment by thierryk** [comment]
We have multiple domain names **because** we chose to go with acss.io but we are worrying that users could go to atomiccss.io or even atomicss.io In other words, if we do not use acss anywhere else than the browser's address bar then why do we need it in the first place?
To me, the "home" link is the domain name. In my opinion, it makes little sense to have Atomic CSS as the "home link" if we promote acss.io

**Comment by src-code** [comment]
This is ultimately a branding issue.  The question is, are we branding the web site, or are we branding the product?
If you look at other frameworks and libraries we use, you'll find that they don't display their domain in their headers.  React, Flux, Fluxible, Node, PHP... even look at oocss.org.  You want your primary header to reflect the name of the product, not how you got there.
The only time I've seen the domain itself placed in the header is for web sites that are marketing the domain rather than a product.  For example: http://www.bottombunkphotography.com/
Once someone finds the web site, they don't necessarily need to remember the domain name.  After all, when you type "Atomic CSS" into your browser's search box, it'll match on the title of the document, which should be "Atomic CSS".  And if the title of the document is that, then the primary header should be as well.
The only reason for acss.io over an alternative, IMHO, is that it's short and easy to put on slides for when we demo this at conferences.
Steve  --  
Steve Carlson 
Sr. Frontend Engineer – Homepages & Verticals
@StevenRCarlson 

     On Thursday, February 26, 2015 12:45 PM, Thierry Koblentz <notifications@github.com> wrote:
   

 We have multiple domain names because we chose to go with acss.io but we are worrying that users could go to atomiccss.io or even atomicss.io In other words, if we do not use acss anywhere else than the browser's address bar then why do we need it in the first place?
To me, the "home" link is the domain name. In my opinion, it makes little sense to have Atomic CSS as the "home link" if we promote acss.io—

**Comment by thierryk** [comment]
> If you look at other frameworks and libraries we use, you'll find that they don't display their domain in their headers.  React, Flux, Fluxible, Node, PHP... even look at oocss.org.  You want your primary header to reflect the name of the product, not how you got there.

it says **react** in the header: http://facebook.github.io/react/
it says **php** in the header of: http://php.net/
it says **nodejs** in the header: http://nodejs.org/
it says **fluxible** in the header: http://fluxible.io/

**oocss** is the [project's name](https://github.com/stubbornella/oocss) so people have a good chance to guess the url for it *but that would not be the case for us since we do not use ACSS anywhere*. How could we expect people to go to acss.io if we do not mention this anywhere?

Once again, **I'm not saying we should use ACSS.io**, what I'm saying is that there is no reason to use that as our domain name if that is not to be found anywhere in the web site. I believe it is important that people get a hint about what's the domain name of your product when it is different than your product. In other words, I'd say it makes sense to use Atomic CSS if we do **not** promote ACSS.io at all; but if we do promote it as the home for Atomic CSS then it needs to show somehow. Because if not, what's the point of using it in the first place?

**Comment by src-code** [comment]
> oocss is the project's name so people have a good chance to guess the url for it but that would not be the case for us since we do not use ACSS anywhere. How could we expect people to go to acss.io if we do not mention this anywhere?

Most people don't navigate by guessing domain names.  They navigate by reading it off a slide at a conference, clicking a link on a web site, or going to a search engine.  So to me, the domain really isn't that important.  SEO, and keeping the domain short and clear (eg, avoiding the "one c" or "two c" problem we had with atomiccss vs atomicss, which could confuse people trying to communicate the domain orally or on slides) is the priority.

For the record though, I originally advocated using something other than acss.io as our primary domain, keeping it as an alias, but I've come to believe that the domain we choose ultimately doesn't matter that much for the above reasons.

**Comment by thierryk** [comment]
Then why not simply dropping ACSS.io ?
It should make things much simpler. We have 2 domains and that's it:
   * atomiccss.io
   * atomicss.io

Of course we promote the former, the latter will take care of the typo we expect people to make.
In my opinion, it solves the problem of communicating a domain name that is different than our product **and** the fact that atomic *is* part of the domain name should be a plus for SE.

**Comment by renatoi** [comment]
Closing since these changes are now in PR #34.

**Pull request closed without merging**
