### PR TITLE
Add paragraph about ATOMIZER WEB

### PR DESCRIPTION
**Pull request by thierryk**
ATOMIZER WEB is the online tool built by Pankaj

### CODE REVIEW

**Comment by src-code** [comment]
I'm not sure if this belongs at the top of the reference page - it might be a better fit under something like our "integrations" section...

**Comment by thierryk** [comment]
@src-code 

"integrations" section? Where is that? Do you mean on the "Atomizer Tool" page?
If I can't easily find it, it may not be the best place for it...

In my opinion, it should be in **people's face** because it is a tool that can really help people figure things out quickly. Originally, I even planned to use some kind of fancy button rather than a simple link&mdash;to make sure people don't miss it.
I really dig that tool and I think we should make sure it has good **visibility**.
If it was just me, I'd even find room on the home page for it!

**Comment by renatoi** [comment]
If it's for good visibility, I recommend adding the Integrations to the top nav bar and making it a separate page.

**Comment by thierryk** [comment]
**test: ignore** 
This is a test as I do not receive any notification for this repo.
Checking if adding my handle changes anything: @thierryk

**Comment by thierryk** [comment]
@src-code could you merge for now, until we find it a better home? 
Or copy/paste the paragraph I added anywhere you want.
(I think it's better to have it somewhere than nowhere at all)

**Comment by src-code** [comment]
@thierryk Promise I'll get this one sorted out in the next couple of days.  Been busy with some other work and haven't had time to think through how to best organize stuff like this, but I'll get to it!

**Comment by src-code** [comment]
Closing this one in favor of #104

**Comment by thierryk** [comment]
@src-code please check my comments following your commits

**Pull request closed without merging**
