### PR TITLE
Home page updates

### PR DESCRIPTION
**Pull request by src-code**
Making the home page more geared toward explaining the reason for Atomic CSS, and also cleaning up some of the wording in the examples.  

I think there's more that can be done here, but this is hopefully a good start.  

cc/ @thierryk @renatoi @dnewcome

### CODE REVIEW

**Comment by redonkulus** [comment]
:+1:

**Comment by src-code** [comment]
I'll open new PRs for the other pages I'm editing, BTW.

**Comment by renatoi** [comment]
:+1: I liked the fact that we make it clear that this is towards component-based frameworks and not for everyone :) A lot of people doesn't quite get the idea of doing it this way until they understand the main concept.

**Comment by src-code** [comment]
@renatoi Yeah!  I was really inspired by that Chris Coyier blog post, where he specifically talks about how React is driving all this backlash against CSS.  So I wanted these changes to echo the points and counterpoints in that blog post...

**Pull request merged**
